// Generated by CoffeeScript 1.9.2
var $, babel, babelify, browserify, clean, coffee, concat, concatCss, gulp, gulpif, minifyCss, notify, order, out, plumber, react, runSequence, sass, source, sourcemaps, src, streamify, swallowError, uglify;

gulp = require('gulp');
$ = require('gulp-load-plugins')();
src = '';
out = '';
order = require("gulp-order");
autoprefixer = require('gulp-autoprefixer');

concat = require("gulp-concat");
clean = require('gulp-clean');
runSequence = require('run-sequence');
coffee = require('gulp-coffee');
gulpif = require('gulp-if');
gulp - (uglify = require('gulp-uglify'));
minifyCss = require('gulp-minify-css');
concatCss = require('gulp-concat-css');
notify = require("gulp-notify");
sass = require('gulp-sass');
sourcemaps = require('gulp-sourcemaps');
babel = require("gulp-babel");
ngAnnotate = require('gulp-ng-annotate');
notify = require("gulp-notify");
browserify = require('browserify');
imagemin = require('gulp-imagemin');
babelify = require('babelify');
source = require('vinyl-source-stream');
streamify = require('gulp-streamify');
plumber = require('gulp-plumber');
spritesmith = require('gulp.spritesmith');

swallowError = function(error) {
    console.log(error.toString());
    notify().write(error.toString());
    this.emit('end');
};

gulp.task("css-min", function() {
    return gulp.src(["src/css/libs/base.css", "src/css/libs/**/*.css"]).pipe(concat("libs.css")).pipe(minifyCss({
        keepBreaks: false,
        processImport: false
    })).pipe(gulp.dest('public/css'));
});


gulp.task('sass', function() {
    gulp;
    return gulp.src('public/css/*.scss').pipe(sourcemaps.init()).pipe(sass({
        errLogToConsole: false,
        onError: function(err) {
            return notify().write(err);
        }
    })).pipe(minifyCss({
        compatibility: 'ie8'
    }))
    .pipe(autoprefixer({
        browsers: ['last 2 versions'],
        cascade: false
    }))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest('public/css'));
});




gulp.task('watch', function() {
    gulp.watch(['css/**/*.scss'], ['sass']);      
    gulp.watch(['src/css/libs/*.css'], ['css-min']);  
});


gulp.task('default', ['sass', 'css-min', 'watch']);
